# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AT_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_s_input = QtWidgets.QLabel(self.centralwidget)
        self.label_s_input.setGeometry(QtCore.QRect(30, 70, 121, 21))
        self.label_s_input.setObjectName("label_s_input")
        self.lineEdit_input = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_input.setGeometry(QtCore.QRect(30, 100, 291, 121))
        self.lineEdit_input.setObjectName("lineEdit_input")
        self.pushButton_go = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_go.setGeometry(QtCore.QRect(30, 230, 89, 25))
        self.pushButton_go.setObjectName("pushButton_go")
        self.label_s_result = QtWidgets.QLabel(self.centralwidget)
        self.label_s_result.setGeometry(QtCore.QRect(30, 290, 121, 21))
        self.label_s_result.setObjectName("label_s_result")
        self.label_output = QtWidgets.QLabel(self.centralwidget)
        self.label_output.setGeometry(QtCore.QRect(30, 320, 281, 171))
        self.label_output.setText("")
        self.label_output.setObjectName("label_output")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_s_input.setText(_translate("MainWindow", "Input command:"))
        self.pushButton_go.setText(_translate("MainWindow", "Go!"))
        self.label_s_result.setText(_translate("MainWindow", "Result:"))
